dist: trusty
language: php
php:
  - '7.4'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - php artisan key:generate
  - npm install

jobs:
  include:
    - stage: "Code Quality"
      script: npm run lint
    - stage: "Build"
      script: npm run production
    - stage: "Test"
      script: vendor/bin/phpunit
    - stage: "Deploy"
      if: branch = master
      script: echo "Deployed"


#script:
#  - vendor/bin/phpunit
#  - npm run lint
#  - npm run production
