dist: trusty
language: php
php:
  - '7.4'

cache:
  directories:
    - node_modules
    - vendor

jobs:
  include:
    - stage: "Setup"
      script: cp .env.travis .env
    - script: composer self-update
    - script: composer install --prefer-dist --no-interaction
    - script: php artisan key:generate
    - script: npm install
    - stage: "Code Quality"
      script: npm run lint
    - stage: "Build"
      script: npm run production
    - stage: "Test"
      script: vendor/bin/phpunit
    - stage: "Deploy"
      if: branch = master
      script: echo "Deployed"
#before_script:
#  - cp .env.travis .env
#  - composer self-update
#  - composer install --prefer-dist --no-interaction --dev
#  - php artisan key:generate
#  - npm install

#script:
#  - vendor/bin/phpunit
#  - npm run lint
#  - npm run production
